config/routes.rb
Kinabird::Application.routes.draw do

  resources :users, :only => [:show, :edit, :update]
  match 'users/:id/more_activities' => 'users#more_activities'

  resources :articles, :only => [:show, :index] do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments, :only => [:create, :index, :destory]
  end
  
  match 'articles/:page/article/:id/like'        => 'articles#like'
  match 'article/:id/like'                       => 'articles#like'

  match 'articles/:page/article/:id/load_more_comments'        => 'articles#load_more_comments'
  match 'article/:id/load_more_comments'                       => 'articles#load_more_comments'

  resources :events, :only => [:index]
  match 'events/type/:type' => 'events#index', :via => :get, :as => :type_events

  resources :magazines, :only => [:show, :index]

  match '/about' => 'static_pages#about'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout'                 => 'sessions#destroy', :as => :signout
  match '/auth/failure'            => 'sessions#failure'

  

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, 
  								:name, 
  								:picurl, 
  								:provider, 
  								:uid
                  :provider_url

  has_many :comments,      dependent: :destroy
  has_many :article_likes, dependent: :destroy

  validates_presence_of :name

  def update_profile(auth)
    user = User.set_user_info(self, auth)
    user.save
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      set_user_info(user, auth)
    end
  end

  def get_activities(count)
    activities = Array.new
    activities << self.comments[0..count] << self.article_likes[0..count]

    # user activities in desc order
    activities.flatten!.sort! {|a,b| b.created_at <=> a.created_at }
    activities = activities[0...count]
  end

  private
  def self.set_user_info(user, auth)
    user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
          user.name = auth['info']['name'] || user.name
          user.email = auth['info']['email'] || user.email
          
          if "linkedin" == auth['provider']
            user.picurl=auth['extra']['raw_info']['pictureUrl'] ||""
            user.provider_url=auth['extra']['raw_info']['publicProfileUrl'] ||""
          elsif "facebook" == auth['provider']
            user.picurl=auth['info']['image']||""
            user.provider_url=auth['extra']['raw_info']['link']||""
          elsif "twitter" == auth['provider']
            user.picurl=auth['info']['image']||""
            user.provider_url=auth['info']['urls']['Twitter']||""
          elsif "tqq" == auth['provider']
            user.picurl=auth['info']['image']||""
            user.provider_url='http://' << auth['info']['urls']['Tqq']||""
          end
      end
      user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => :show

  def edit
    @user = User.find(params[:id])
    can_modify?(@user)
  end
  
  def update
    @user = User.find(params[:id])
    can_modify?(@user)
    if @user.update_attributes(params[:user])
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.get_activities(20)
  end

  def more_activities
    @user = User.find(params[:id])
    
    @activities = @user.get_activities(40)
    respond_to do |format|
        format.js
    end
  end

  private
  def can_modify? (user)
    if current_user.id != user.id
      redirect_to root_url, :alert => 'You cannot access to this page.'
    end
  end

end

app/helpers/user_helper.rb
module UserHelper
  def get_edit_submit_text
	  if user_signed_in? 
  		  "Submit" 
  	  else
  		  "Sign in"
  	  end
	end

	def logo_name
		if "linkedin" == @user.provider
			"in.png"		
		elsif "facebook" == @user.provider
			"fb.png"			
		elsif "twitter" == @user.provider
			"tw.png"	
		elsif "tqq" == @user.provider
			"tqq.png"					
		end
	end
end

app/views/users/_user_activities.html.erb
<div id="user-activities">
	<% @activities.each do |act| %>
		<% if act.instance_of?(Comment) %>
			<%= render :partial => "users/user_comments", 
								 :locals => {:act => act} %>
		<% elsif act.instance_of?(ArticleLike) %>
			<%= render :partial => "users/user_article_likes", 
								:locals => {:act => act} %>
		<% end %>
	<% end %>
		
	<!-- Loads more acts -->
	<% unless @activities.first.nil? %>
	  <% if @activities.size>10 && @activities.size<=20 %>
	    <div class="comment-load-more" 
	         id="load-more-activities-btn"
	         onclick='load_more_activities(<%= @activities.first.user_id %>)'>
	        Load more...
	    </div>
	  <% end %>
  <% end %>

<div>

app/views/users/_user_article_likes.html.erb
<div class="user-activity">
	<span class="item-attr">
  	<span class="item-like item-liked pull-left"%></span>
  	新闻
	</span>

	<span class="activity-time-ago">
  		<%= (time_ago_in_words(act.created_at) << ' ago')%>
  </span>

	<div class="activity-content">
		<span class="activity-article-title">
  		<%= link_to act.article.title, article_path(act.article) %>
  	</span>
  	
  	<div class="activity-article-summary">
  		<%= act.article.summary %>
  	</div>
	</div>
</div>

app/views/users/_user_comments.html.erb
<div class="user-activity">
	<span class="item-attr">
  	<span class="item-comment pull-left"%></span>
  	评论
	</span>

  <div class="comment-content">
    "<%= act.content%>"
    <span class="activity-time-ago">
      <%= (time_ago_in_words(act.created_at) << ' ago')%>
    </span>
  </div>

	<div class="activity-content">
		<span class="activity-article-title">
  		<%= link_to act.article.title, article_path(act.article) %>
  	</span>
  	
  	<div class="activity-article-summary">
  		<%= act.article.summary %>
  	</div>
	</div>
</div>

app/views/users/edit.html.erb
<h4>User: <%= @user.name %></h4>

<div class="user-img">
	<%= image_tag @user.picurl if @user.picurl && !@user.picurl.empty? %>
</div>

<%= form_for(@user) do |f| %>
  <span class="add-on"><i class="icon-envelope"></i></span>
  <%= f.text_field :email %>
  <br />
  <%= f.submit get_edit_submit_text %>
<% end %>

app/views/users/more_activities.js.erb
<% if current_user %>
	$('#user-activities').html(
		"<%=j render :partial => 'users/user_activities', :collection => @activities %>");

	$("abbr.timeago").timeago();
<% end %>

app/views/users/show.html.erb
<div class="row">
    <div class="span4">
				<span class="user-header-text"><h3><%= @user.name %></h3></span>

				<div class="user-img">
					<%= image_tag @user.picurl unless @user.picurl.empty?%>
				</div>

				<div class="user-details">
					<i class="icon-envelope"></i><%= ": "%><%= mail_to @user.email%>

					<div class="provider-logo">
						<%= link_to image_tag(logo_name), @user.provider_url, :target => "_blank" %>
					</div>
				</div>
    </div>

    <div class="span8">
    	<div class="panel">
				<%= render :partial => 'users/user_activities' %>
			</div>
		</div>
</div>