config/routes.rb
Kinabird::Application.routes.draw do

  resources :users, :only => [:show, :edit, :update]
  match 'users/:id/more_activities' => 'users#more_activities'

  resources :articles, :only => [:show, :index] do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments, :only => [:create, :index, :destory]
  end
  
  match 'articles/:page/article/:id/like'        => 'articles#like'
  match 'article/:id/like'                       => 'articles#like'

  match 'articles/:page/article/:id/load_more_comments'        => 'articles#load_more_comments'
  match 'article/:id/load_more_comments'                       => 'articles#load_more_comments'

  resources :events, :only => [:index]
  match 'events/type/:type' => 'events#index', :via => :get, :as => :type_events

  resources :magazines, :only => [:show, :index]

  match '/about' => 'static_pages#about'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout'                 => 'sessions#destroy', :as => :signout
  match '/auth/failure'            => 'sessions#failure'

  

  root :to => 'home#index'

end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  attr_accessible :from_date, 
  								:super_market, 
  								:to_date, 
  								:magazine_type,
  								:logo_url,
  								:first_img_url,
  								:page_count

	has_many :magazine_pages


	# magazine hash, key: category
	def self.latest_magazine_hash
		magazines = Magazine.where("to_date > ?", DateTime.now).order("super_market")

		magazine_hash = Hash.new
		magazines.each do |m|
			if !magazine_hash.has_key?(m.magazine_type)
				magazine_hash[m.magazine_type] = [m]
			else
				magazine_hash[m.magazine_type] << m
			end 
		end

		magazine_hash
	end

end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController

	def index
		@magazines_hash = Magazine.latest_magazine_hash
	end

	def show
		@magazine = Magazine.find(params[:id])
		@magazine_pages = @magazine.magazine_pages.page(params[:page])
	end
end

app/helpers/magazines_helper.rb
# encoding: utf-8

module MagazinesHelper
	def active_item(page_number)
		# 12 items each page, the 1st one is active
		"active" if page_number%12 == 1
	end

	def get_from_to_date_str(magazine)
		magazine.from_date.strftime('%d/%m') << ' - ' << magazine.to_date.strftime('%d/%m')
	end

	def get_magazine_type(category)
	  case category
	  when "Dagligvarer"
	    "超市"
	  when "Autoudstyr"
	    "摩托汽配"
	  when "Byggemarkeder"
	    "DIY"
	  when "Grænsehandel"
	    "边境商店 - 超赞!"
	  when "Hvidevarer/elektronik"
	    "电器产品"
	  when "Isenkram"
	    "家居"
	  when "Legetøj/Hobby"
	    "玩具"
	  when "Møbler/indretning"
	    "家具装潢 "
	  when "Pc/elektronik"
	    "PC电子"
	  when "Stormagasiner"
	    "商场"
	  when "Bøger/kontorartikler"
	  	"办公用品"
	  else
	    "其他"
	  end
	end

end

app/views/magazines/_magazine.html.erb
<div class="panel magazine-panel-wapper <%= span_class%>" 
		 style="background-color: <%= bg_color%>">
		 
	<div class="magazine-category-header">
		<%= get_magazine_type(category) %>
	</div>

  <% @magazines_hash[category].each do |magazine| %>
    <div class="magazine-box pull-left">
      <%= magazine.logo_url ? (image_tag magazine.logo_url) : magazine.super_market %>
      <br>
      <%= link_to  get_from_to_date_str(magazine), magazine_path(magazine.id) %>
    </div>
  <% end if @magazines_hash[category]%>
</div>

app/views/magazines/index.html.erb
<div class="row">
    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Stormagasiner', 
                           :span_class =>'span1', 
                           :bg_color =>'#D4D7DB'} %> 

    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Møbler/indretning', 
                           :span_class =>'span4', 
                           :bg_color =>'#f2f2f2'} %> 

    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Dagligvarer', 
                           :span_class =>'span6', 
                           :bg_color =>'#D4D7DB'} %>      
</div>

<div class="row">
    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Pc/elektronik', 
                           :span_class =>'span4', 
                           :bg_color =>'#f2f2f2'} %>

    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Isenkram', 
                           :span_class =>'span4',
                           :bg_color =>'#D4D7DB'} %>

    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Hvidevarer/elektronik', 
                           :span_class =>'span3', 
                           :bg_color =>'#f2f2f2'} %>
</div>

<div class="row">
    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Legetøj/Hobby', 
                           :span_class =>'span3', 
                           :bg_color =>'#D4D7DB'} %>

    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Byggemarkeder', 
                           :span_class =>'span8', 
                           :bg_color =>'#f2f2f2'} %>   
</div>

<div class="row">
    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Autoudstyr', 
                           :span_class =>'span1', 
                           :bg_color =>'#D4D7DB'} %>

    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Bøger/kontorartikler', 
                           :span_class =>'span1', 
                           :bg_color =>'#f2f2f2'} %>

    <%= render :partial => 'magazines/magazine', 
               :locals => {:category => 'Grænsehandel', 
                           :span_class =>'span9', 
                           :bg_color =>'#D4D7DB'} %>    
</div>

app/views/magazines/show.html.erb
<div class="row">

    <div class="span8">
    	<div class="magazine-header">
    		<%= "#{@magazine.super_market} 
                (#{@magazine.from_date.to_date} ---- #{@magazine.to_date.to_date})" %>
    	</div>
    	
        <div id="magazine-carousel" class="carousel slide" data-interval="false">
          <!-- Carousel items -->
          <div class="carousel-inner">
            <% @magazine_pages.each do |page| %>
                <div id="item-<%= page.page_number%>" 
                     class="item <%= active_item(page.page_number) %>">
                    <%= image_tag(page.image_url) %>
                </div>
            <% end %>
          </div>
          <!-- Carousel nav -->
          <a class="carousel-control left"  href="#magazine-carousel" data-slide="prev">&lsaquo;</a>
          <a class="carousel-control right" href="#magazine-carousel" data-slide="next">&rsaquo;</a>
        </div>

        <div class="data-source pull-right">
            Data source:
            <%= link_to "www.tilbudsugen.dk", "http://www.tilbudsugen.dk", :target => "_blank" %>
        </div>
    </div>

    <div class="span4">
        <div class="page"><%= paginate @magazine_pages %></div>
        <span class="magazine-page-thumb">
        	<% @magazine_pages.each do |page| %>
                <%= link_to image_tag(page.image_url, :onclick => "set_image('#{page.page_number}')"), 
                            'javascript:void(0)' %>
            <% end %>
        </span>
        <div class="page"><%= paginate @magazine_pages %></div>
    </div>
</div>