config/routes.rb
Kinabird::Application.routes.draw do

  resources :users, :only => [:show, :edit, :update]
  match 'users/:id/more_activities' => 'users#more_activities'

  resources :articles, :only => [:show, :index] do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments, :only => [:create, :index, :destory]
  end
  
  match 'articles/:page/article/:id/like'        => 'articles#like'
  match 'article/:id/like'                       => 'articles#like'

  match 'articles/:page/article/:id/load_more_comments'        => 'articles#load_more_comments'
  match 'article/:id/load_more_comments'                       => 'articles#load_more_comments'

  resources :events, :only => [:index]
  match 'events/type/:type' => 'events#index', :via => :get, :as => :type_events

  resources :magazines, :only => [:show, :index]

  match '/about' => 'static_pages#about'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout'                 => 'sessions#destroy', :as => :signout
  match '/auth/failure'            => 'sessions#failure'

  

  root :to => 'home#index'

end

app/views/layouts/_footer.html.erb
<div>
    Made with 
    <span class="item-attr">
      <span class="item-like item-liked"></span>in CPH
    </span>
</div>

<nav>
  <!-- Social like btns, show in Home page -->
  <% if content_for(:title).include? ("Home") %>
    <ul>
      <div class="social-like">
        <div class="g-plusone" data-size="medium"></div>
      </div>
      <div class="fb-like social-like" 
          data-href="http://www.lewen.dk" 
          data-send="false" 
          data-layout="button_count" 
          data-width="100" 
          data-show-faces="true">
      </div>
      <div class="social-like">
        <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a> 
      </div>
    </ul>
  <% end %>

  <ul>
    <li><%= link_to "About", about_path %></li>
  </ul>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<span class="pull-left lewen-logo">
  <%= link_to image_tag("lewen.png"), root_path %>
</span>

<ul class="nav">

  <li class="dropdown">
    <a class="dropdown-toggle header-item" data-toggle="dropdown" href="#">
      新闻ing - News
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu header-subitem">
      <li>
        <%= link_to "中文新闻 - Chinese News", articles_path(:lang => "CH") %>
      </li>
      <li>
        <%= link_to "英语新闻 - English News", articles_path(:lang => "EN") %>
      </li>
      <li>
        <%= link_to "所有新闻 - All", articles_path %>
      </li>
    </ul>
  </li>

  <li class="dropdown">
    <a class="dropdown-toggle header-item" data-toggle="dropdown" href="#">
      活动 - Events
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu header-subitem">      
      <li>
        <%= link_to "音乐会 - Music", type_events_path(:type => 'Music') %>
      </li>
      <li>
        <%= link_to "体育 - Sport", type_events_path(:type => 'Sport') %>
      </li>
      <li>
        <%= link_to "剧场 - Teater", type_events_path(:type => 'Teater') %>
      </li>
      <li>
        <%= link_to "会议，课程 - Conference, Classes", type_events_path(:type => 'Conference') %>
      </li>
      <li>
        <%= link_to "Networking, Social", type_events_path(:type => 'Networking') %>
      </li>
      <li>
        <%= link_to "其他 - Others", type_events_path(:type => 'Other') %>
      </li>
    </ul>
  </li>

  <li class="header-item">
    <%= link_to "折扣控", magazines_path %>
  </li>
</ul>



<ul class="nav pull-right">

  <% unless user_signed_in? %>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        Sign in with
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li class="pull-right signin-logo" data-toggle="tooltip" title="Connect via TQQ">
          <%= link_to image_tag("tweibo.png", :size=> "115x30"), "/auth/tqq" %>
        </li>
        <li class="pull-right signin-logo" data-toggle="tooltip" title="Connect via LinkedIn">
          <%= link_to image_tag("linkedin.jpg", :size=> "115x30"), "/auth/linkedin" %>
        </li>
        <li class="pull-right signin-logo" data-toggle="tooltip" title="Connect via Facebook">
          <%= link_to image_tag("facebook.gif", :size=> "115x30"), "/auth/facebook" %>
        </li>
        <li class="pull-right signin-logo" data-toggle="tooltip" title="Connect via Facebook">
          <%= link_to image_tag("twitter.png", :size=> "115x30"), "/auth/twitter" %>
        </li>
        
      </ul>
    </li>
  <% end %>  

  <% if user_signed_in? %>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <span class="dropdown-user">
          <%= (image_tag current_user.picurl) if current_user.picurl && !current_user.picurl.empty? %>
        </span>
        <%= current_user.name %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to "Your Profile", user_path(current_user) %>
        </li>
        <li>
          <%= link_to 'Logout', signout_path %>
        </li>
      </ul>
    </li>
  <% end %> 
</ul>

app/views/layouts/_signup_modal.html.erb
<div id="signup-modal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h5>Sign in with:</h5>
  </div>

  <div class="modal-body">
  	<div class="signup-logos">
      <span class="logo" data-toggle="tooltip" title="Connect via LinkedIn">
        <%= link_to image_tag("tweibo.png", :size=> "120x30"), "/auth/tqq" %>
      </span>
      <br><br>
    	<span class="logo" data-toggle="tooltip" title="Connect via LinkedIn">
    		<%= link_to image_tag("linkedin.jpg", :size=> "120x30"), "/auth/linkedin" %>
    	</span>
    	<br><br>
    	<span class="logo" data-toggle="tooltip" title="Connect via Facebook">
    		<%= link_to image_tag("facebook.gif", :size=> "120x30"), "/auth/facebook" %> 
    	</span>
      <br><br>
      <span class="logo" data-toggle="tooltip" title="Connect via Twitter">
        <%= link_to image_tag("twitter.png", :size=> "120x30"), "/auth/twitter" %> 
      </span>
    </div>     
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><%= content_for?(:title) ? yield(:title) : "樂聞" %></title>
    <meta name="title" content="<%= content_for?(:title) ? yield(:title) : "樂聞" %>">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "新闻导读,本地活动,超市打折,帮助在丹麦专业人士了解本地信息" %>">
    <meta name="keywords" content="丹麦, 丹麦信息, 丹麦新闻, 哥本哈根, 新闻, 活动, 乐闻, 丹麦语, Denmark, Copenhagen, Arhus, 奥胡斯, 华人, 丹麦华人">
    <meta name="author" content="丹麦 乐闻">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- Google + -->
    <link rel="canonical" href=<%= content_for?(:url) ? yield(:url) : "http://www.lewen.dk" %> />
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= render 'layouts/signup_modal' %>
              <%= yield %>
            </div>
          </div>
          <footer class="footer">
            <%= render 'layouts/footer' %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39730048-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>